### ISSUE TITLE
Name going backwards

### ISSUE THREAD

**Issue by MaudeTeacup** [ChildrenOfUr/coUclient#133]
Hi

when I walk to the right my name is ok but I go to the left and it flips so is a mirror image.

![lady snow 1](https://cloud.githubusercontent.com/assets/8277572/4176286/b8fa10e8-35fb-11e4-9f4a-959f520c00b5.png)
![lady snow 2](https://cloud.githubusercontent.com/assets/8277572/4176288/bc4670ca-35fb-11e4-852a-2cae448c306f.png)

**Comment by ppvk** [comment]
I've heard this was fixed, did you do it @RobertMcDermot , or @Klikini?

**Comment by RobertMcDermot** [comment]
I don't remember making an effort to fix this particular issue. Will have to verify if it's still a bug.

**Comment by Klikini** [comment]
I didn't fix it. At least not that I know of/not on purpose. Spontaneous
bug fixing! Did slackbot finally keep its word?

**Comment by RobertMcDermot** [comment]
I just confirmed that this should now work properly. The changes were pushed live. If you still have issues, try reloading with ctrl+f5 to clear the cache.

**Comment by angelicacid** [comment]
It was being caused by running the game in IE instead of chrome.
angelic acid 

     On Saturday, January 10, 2015 7:36 PM, Robert McDermot <notifications@github.com> wrote:
   

 I just confirmed that this should now work properly. The changes were pushed live. If you still have issues, try reloading with ctrl+f5 to clear the cache.—
